name: "restaurant-app"

services:
  restaurant-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=restaurant-db'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - 'restaurant-db-volume:/var/lib/postgresql/data'

  restaurant-app:
    image: 'restaurant-app:latest'
    env_file: .env
    depends_on:
      - restaurant-db
    ports:
      - '8080:8080'

volumes:
  restaurant-db-volume: