name: "restaurant-app"

services:
  minio:
    ports:
      - '9000:9000'
      - '9001:9001'
    container_name: 'minio-obj-storage'
    tty: true
    env_file: ./.env
    volumes:
      - 'minio-volume:/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
    image: 'quay.io/minio/minio'
    command: 'server /data --console-address ":9001"'

  restaurant-db:
    image: 'postgres:latest'
    tty: true
    env_file: ./.env
    container_name: 'restaurant-db'
    environment:
      - 'POSTGRES_DB=restaurant-db'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - 'restaurant-db-volume:/var/lib/postgresql/data'

  restaurant-app:
    image: 'restaurant-app:latest'
    container_name: 'restaurant-app'
    tty: true
    env_file: ./.env
    depends_on:
      - restaurant-db
      - minio
    ports:
      - '8080:8080'

volumes:
  restaurant-db-volume:
  minio-volume: