spring:
  application:
    name: "restaurant-app-backend"
  datasource:
    url: "jdbc:postgresql://restaurant-db:5432/restaurant-db"
    driver-class-name: "org.postgresql.Driver"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
  servlet:
    multipart:
      max-file-size: "15MB"
      max-request-size: "15MB"
server:
  port: 8080